pre-release-commit-message = "Release {{crate_name}} {{version}}"
no-dev-version = true
tag-message = "Release {{crate_name}} {{version}}"
tag-name = "{{crate_name}}-{{version}}"
sign-commit = true
sign-tag = true

pre-release-replacements = [
  {file="README.md", search="spirv = .*", replace="{{crate_name}} = \"{{version_without_metadata}}\""},
  {file="../rspirv/Cargo.toml", search="spirv = \\{ version = \".*\", path = \"../spirv\" \\}", replace="{{crate_name}} = { version = \"{{version_without_metadata}}\", path = \"../spirv\" }" },
]


